USE `MEALWITH`;

INSERT INTO recipe_category (name)
VALUES ('Breakfast'),
 ('Dessert'),
 ('Main course'),
 ('Side dish'),
 ('Snack'),
 ('Soup');

INSERT INTO ingredient_category (name)
VALUES ('Meat / Fish'),
 ('Fruits / Vegetables'),
 ('Dairy products'),
 ('Grocery');

INSERT INTO recipes (category_id, id_author, name, picture)
VALUES (3,1,'Brussel Sprouts in Bacon and Garlic Sauce','ChickenFajitaStuffedBellPepper.png'),
       (3,1,'Chicken Fajita Stuffed Bell Pepper','ChickenFajitaStuffedBellPepper.png'),
       (2,1,'OREO Cookie Balls – Snowman','OREOCookieBalls.png'),
       (2,1,'Dessert Apple Rings With Cinnamon Cream Syrup','/DessertAppleRingsWithCinnamonCreamSyrup.png'),
       (2,1,'Triple Citrus Cake','TripleCitrusCake.png'),
       (1,1,'Holiday Egg Nog','HolidayEggNog.png'),
       (3,1,'Layered Poppy Seed Pastries','LayeredPoppySeedPastries.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (5,1,'Chicken 65','Chicken65.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png'),
       (6,1,'Creamy Broccoli Spinach Soup','CreamyBroccoliSpinachSoup.png');

INSERT INTO origin (country,region)
VALUES ('Andorra', 'Europe'),
       ('United Arab Emirates', 'Asia'),
       ('Afghanistan', 'Asia'),
       ('Antigua and Barbuda', 'North America'),
       ('Anguilla', 'North America'),
       ('Albania', 'Europe'),
       ('Armenia', 'Asia'),
       ('Angola', 'Africa'),
       ('Antarctica', 'Antarctica'),
       ('Argentina', 'South America'),
       ('American Samoa', 'Oceania'),
       ('Austria', 'Europe'),
       ('Australia', 'Oceania'),
       ('Aruba', 'North America'),
       ('Åland', 'Europe'),
       ('Azerbaijan', 'Asia'),
       ('Bosnia and Herzegovina', 'Europe'),
       ('Barbados', 'North America'),
       ('Bangladesh', 'Asia'),
       ('Belgium', 'Europe'),
       ('Burkina Faso', 'Africa'),
       ('Bulgaria', 'Europe'),
       ('Bahrain', 'Asia'),
       ('Burundi', 'Africa'),
       ('Benin', 'Africa'),
       ('Saint Barthélemy', 'North America'),
       ('Bermuda', 'North America'),
       ('Brunei', 'Asia'),
       ('Bolivia', 'South America'),
       ('Bonaire, Sint Eustatius, and Saba', 'North America'),
       ('Brazil', 'South America'),
       ('Bahamas', 'North America'),
       ('Bhutan', 'Asia'),
       ('Bouvet Island', 'Antarctica'),
       ('Botswana', 'Africa'),
       ('Belarus', 'Europe'),
       ('Belize', 'North America'),
       ('Canada', 'North America'),
       ('Cocos [Keeling] Islands', 'Asia'),
       ('DR Congo', 'Africa'),
       ('Central African Republic', 'Africa'),
       ('Congo Republic', 'Africa'),
       ('Switzerland', 'Europe'),
       ('Ivory Coast', 'Africa'),
       ('Cook Islands', 'Oceania'),
       ('Chile', 'South America'),
       ('Cameroon', 'Africa'),
       ('China', 'Asia'),
       ('Colombia', 'South America'),
       ('Costa Rica', 'North America'),
       ('Cuba', 'North America'),
       ('Cabo Verde', 'Africa'),
       ('Curaçao', 'North America'),
       ('Christmas Island', 'Oceania'),
       ('Cyprus', 'Europe'),
       ('Czechia', 'Europe'),
       ('Germany', 'Europe'),
       ('Djibouti', 'Africa'),
       ('Denmark', 'Europe'),
       ('Dominica', 'North America'),
       ('Dominican Republic', 'North America'),
       ('Algeria', 'Africa'),
       ('Ecuador', 'South America'),
       ('Estonia', 'Europe'),
       ('Egypt', 'Africa'),
       ('Western Sahara', 'Africa'),
       ('Eritrea', 'Africa'),
       ('Spain', 'Europe'),
       ('Ethiopia', 'Africa'),
       ('Finland', 'Europe'),
       ('Fiji', 'Oceania'),
       ('Falkland Islands', 'South America'),
       ('Micronesia', 'Oceania'),
       ('Faroe Islands', 'Europe'),
       ('France', 'Europe'),
       ('Gabon', 'Africa'),
       ('United Kingdom', 'Europe'),
       ('Grenada', 'North America'),
       ('Georgia', 'Asia'),
       ('French Guiana', 'South America'),
       ('Guernsey', 'Europe'),
       ('Ghana', 'Africa'),
       ('Gibraltar', 'Europe'),
       ('Greenland', 'North America'),
       ('Gambia', 'Africa'),
       ('Guinea', 'Africa'),
       ('Guadeloupe', 'North America'),
       ('Equatorial Guinea', 'Africa'),
       ('Greece', 'Europe'),
       ('South Georgia and South Sandwich Islands', 'Antarctica'),
       ('Guatemala', 'North America'),
       ('Guam', 'Oceania'),
       ('Guinea-Bissau', 'Africa'),
       ('Guyana', 'South America'),
       ('Hong Kong', 'Asia'),
       ('Heard Island and McDonald Islands', 'Antarctica'),
       ('Honduras', 'North America'),
       ('Croatia', 'Europe'),
       ('Haiti', 'North America'),
       ('Hungary', 'Europe'),
       ('Indonesia', 'Asia'),
       ('Ireland', 'Europe'),
       ('Israel', 'Asia'),
       ('Isle of Man', 'Europe'),
       ('India', 'Asia'),
       ('British Indian Ocean Territory', 'Asia'),
       ('Iraq', 'Asia'),
       ('Iran', 'Asia'),
       ('Iceland', 'Europe'),
       ('Italy', 'Europe'),
       ('Jersey', 'Europe'),
       ('Jamaica', 'North America'),
       ('Jordan', 'Asia'),
       ('Japan', 'Asia'),
       ('Kenya', 'Africa'),
       ('Kyrgyzstan', 'Asia'),
       ('Cambodia', 'Asia'),
       ('Kiribati', 'Oceania'),
       ('Comoros', 'Africa'),
       ('St Kitts and Nevis', 'North America'),
       ('North Korea', 'Asia'),
       ('South Korea', 'Asia'),
       ('Kuwait', 'Asia'),
       ('Cayman Islands', 'North America'),
       ('Kazakhstan', 'Asia'),
       ('Laos', 'Asia'),
       ('Lebanon', 'Asia'),
       ('Saint Lucia', 'North America'),
       ('Liechtenstein', 'Europe'),
       ('Sri Lanka', 'Asia'),
       ('Liberia', 'Africa'),
       ('Lesotho', 'Africa'),
       ('Lithuania', 'Europe'),
       ('Luxembourg', 'Europe'),
       ('Latvia', 'Europe'),
       ('Libya', 'Africa'),
       ('Morocco', 'Africa'),
       ('Monaco', 'Europe'),
       ('Moldova', 'Europe'),
       ('Montenegro', 'Europe'),
       ('Saint Martin', 'North America'),
       ('Madagascar', 'Africa'),
       ('Marshall Islands', 'Oceania'),
       ('North Macedonia', 'Europe'),
       ('Mali', 'Africa'),
       ('Myanmar', 'Asia'),
       ('Mongolia', 'Asia'),
       ('Macao', 'Asia'),
       ('Northern Mariana Islands', 'Oceania'),
       ('Martinique', 'North America'),
       ('Mauritania', 'Africa'),
       ('Montserrat', 'North America'),
       ('Malta', 'Europe'),
       ('Mauritius', 'Africa'),
       ('Maldives', 'Asia'),
       ('Malawi', 'Africa'),
       ('Mexico', 'North America'),
       ('Malaysia', 'Asia'),
       ('Mozambique', 'Africa'),
       ('Namibia', 'Africa'),
       ('New Caledonia', 'Oceania'),
       ('Niger', 'Africa'),
       ('Norfolk Island', 'Oceania'),
       ('Nigeria', 'Africa'),
       ('Nicaragua', 'North America'),
       ('Netherlands', 'Europe'),
       ('Norway', 'Europe'),
       ('Nepal', 'Asia'),
       ('Nauru', 'Oceania'),
       ('Niue', 'Oceania'),
       ('New Zealand', 'Oceania'),
       ('Oman', 'Asia'),
       ('Panama', 'North America'),
       ('Peru', 'South America'),
       ('French Polynesia', 'Oceania'),
       ('Papua New Guinea', 'Oceania'),
       ('Philippines', 'Asia'),
       ('Pakistan', 'Asia'),
       ('Poland', 'Europe'),
       ('Saint Pierre and Miquelon', 'North America'),
       ('Pitcairn Islands', 'Oceania'),
       ('Puerto Rico', 'North America'),
       ('Palestine', 'Asia'),
       ('Portugal', 'Europe'),
       ('Palau', 'Oceania'),
       ('Paraguay', 'South America'),
       ('Qatar', 'Asia'),
       ('Réunion', 'Africa'),
       ('Romania', 'Europe'),
       ('Serbia', 'Europe'),
       ('Russia', 'Europe'),
       ('Rwanda', 'Africa'),
       ('Saudi Arabia', 'Asia'),
       ('Solomon Islands', 'Oceania'),
       ('Seychelles', 'Africa'),
       ('Sudan', 'Africa'),
       ('Sweden', 'Europe'),
       ('Singapore', 'Asia'),
       ('Saint Helena', 'Africa'),
       ('Slovenia', 'Europe'),
       ('Svalbard and Jan Mayen', 'Europe'),
       ('Slovakia', 'Europe'),
       ('Sierra Leone', 'Africa'),
       ('San Marino', 'Europe'),
       ('Senegal', 'Africa'),
       ('Somalia', 'Africa'),
       ('Suriname', 'South America'),
       ('South Sudan', 'Africa'),
       ('São Tomé and Príncipe', 'Africa'),
       ('El Salvador', 'North America'),
       ('Sint Maarten', 'North America'),
       ('Syria', 'Asia'),
       ('Eswatini', 'Africa'),
       ('Turks and Caicos Islands', 'North America'),
       ('Chad', 'Africa'),
       ('French Southern Territories', 'Antarctica'),
       ('Togo', 'Africa'),
       ('Thailand', 'Asia'),
       ('Tajikistan', 'Asia'),
       ('Tokelau', 'Oceania'),
       ('Timor-Leste', 'Oceania'),
       ('Turkmenistan', 'Asia'),
       ('Tunisia', 'Africa'),
       ('Tonga', 'Oceania'),
       ('Turkey', 'Asia'),
       ('Trinidad and Tobago', 'North America'),
       ('Tuvalu', 'Oceania'),
       ('Taiwan', 'Asia'),
       ('Tanzania', 'Africa'),
       ('Ukraine', 'Europe'),
       ('Uganda', 'Africa'),
       ('U.S. Minor Outlying Islands', 'Oceania'),
       ('United States', 'North America'),
       ('Uruguay', 'South America'),
       ('Uzbekistan', 'Asia'),
       ('Vatican City', 'Europe'),
       ('St Vincent and Grenadines', 'North America'),
       ('Venezuela', 'South America'),
       ('British Virgin Islands', 'North America'),
       ('U.S. Virgin Islands', 'North America'),
       ('Vietnam', 'Asia'),
       ('Vanuatu', 'Oceania'),
       ('Wallis and Futuna', 'Oceania'),
       ('Samoa', 'Oceania'),
       ('Kosovo', 'Europe'),
       ('Yemen', 'Asia'),
       ('Mayotte', 'Africa'),
       ('South Africa', 'Africa'),
       ('Zambia', 'Africa'),
       ('Zimbabwe', 'Africa');

INSERT INTO ingredients (category_id,name,origin_id,unit_id,price,temp_min,temp_max,shelf_life, picture)
VALUES (2,'Pineapple',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Pineapple.png'),
       (2,'Kiwi',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Kiwi.png'),
       (4,'Onion',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Onion.png'),
       (2,'Orange',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Orange.png'),
       (2,'Cucumber',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Cucumber.png'),
       (2,'Tomato',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Tomato.png'),
       (2,'Melon',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Melon.png'),
       (3,'Pasta',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Pasta.png'),
       (2,'Pepper',ROUND((1+RAND()*(250-1))),1,ROUND((1+RAND()*(30-1))),ROUND((10+RAND()*(20-10))),ROUND((21+RAND()*(35-21))),ROUND((1+RAND()*(15-1))),'Pepper.png');

INSERT INTO `users` (`id`, `email`, `firstname`, `lastname`, `password`, `roles`)
VALUES (1, 'test@test.fr', 'Testeur', 'Testeur', '$argon2id$v=19$m=65536,t=4,p=1$VzMwM0V0MGRILkFjTHJHYQ$+Aae6cVX7XUCKsWeR7uykM3uTVFg/2XT5CJD/uCL0I0', '["ROLE_USER"]'),
       (2, 'testguillaume@test.fr', 'Firstname', 'Lastname', '$argon2id$v=19$m=65536,t=4,p=1$VzMwM0V0MGRILkFjTHJHYQ$+Aae6cVX7XUCKsWeR7uykM3uTVFg/2XT5CJD/uCL0I0', '["ROLE_USER"]');

INSERT INTO `units` (`id`, `type`)
VALUES (1, 'kilogram'),
       (2, 'piece');
